// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiQ5Kg3R2_hdUuneZ7rmBMcHnwM9VLoKk',
    appId: '1:262044557269:web:7a026f692978a01d6a275c',
    messagingSenderId: '262044557269',
    projectId: 'mock-ai-f7fd4',
    authDomain: 'mock-ai-f7fd4.firebaseapp.com',
    storageBucket: 'mock-ai-f7fd4.firebasestorage.app',
    measurementId: 'G-Y83KM0HQD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGNHCSm4v85PvfASmHWvRNNB2J7otIt-s',
    appId: '1:262044557269:android:1d2977134c10f0816a275c',
    messagingSenderId: '262044557269',
    projectId: 'mock-ai-f7fd4',
    storageBucket: 'mock-ai-f7fd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG759ypPtZdWO-4Ra6UlbPDQYwCysdQRQ',
    appId: '1:262044557269:ios:0dd3f550d335a06d6a275c',
    messagingSenderId: '262044557269',
    projectId: 'mock-ai-f7fd4',
    storageBucket: 'mock-ai-f7fd4.firebasestorage.app',
    iosBundleId: 'com.example.mockAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG759ypPtZdWO-4Ra6UlbPDQYwCysdQRQ',
    appId: '1:262044557269:ios:0dd3f550d335a06d6a275c',
    messagingSenderId: '262044557269',
    projectId: 'mock-ai-f7fd4',
    storageBucket: 'mock-ai-f7fd4.firebasestorage.app',
    iosBundleId: 'com.example.mockAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiQ5Kg3R2_hdUuneZ7rmBMcHnwM9VLoKk',
    appId: '1:262044557269:web:652e5ed0e46b52856a275c',
    messagingSenderId: '262044557269',
    projectId: 'mock-ai-f7fd4',
    authDomain: 'mock-ai-f7fd4.firebaseapp.com',
    storageBucket: 'mock-ai-f7fd4.firebasestorage.app',
    measurementId: 'G-G0SRV3PCD5',
  );
}
