name: mock_ai
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  file_picker: ^8.0.7
  http: ^1.1.0
  permission_handler: ^11.3.1
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  flutter_sound: ^9.2.13
  flutter_launcher_icons: ^0.14.4
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.4
  email_otp: 3.0.2
  shared_preferences: ^2.2.2
  cloud_firestore: ^4.15.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
